// <auto-generated />
using ControleFacil.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleFacil.Api.Migrations
{
    [DbContext(typeof(ApplicationContex))]
    [Migration("20240910185943_CriarEntidadeApagar")]
    partial class CriarEntidadeApagar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleFacil.Api.Damain.Models.Apagar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("DataCadastro")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("DataInativacao")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("DataPagamento")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("DataRefencia")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("DataVencimento")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<long>("IdNL")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<double>("ValorOriginal")
                        .HasColumnType("double precision");

                    b.Property<double>("ValorPago")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("IdNL");

                    b.HasIndex("IdUser");

                    b.ToTable("Apagar", (string)null);
                });

            modelBuilder.Entity("ControleFacil.Api.Damain.Models.NaturezaLancamento", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("DataCadastro")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("DataInativacao")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.HasKey("ID");

                    b.HasIndex("IdUser");

                    b.ToTable("naturezalancamento", (string)null);
                });

            modelBuilder.Entity("ControleFacil.Api.Damain.Models.Usuario", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("DataCadastro")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("DataInativacao")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.HasKey("ID");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("ControleFacil.Api.Damain.Models.Apagar", b =>
                {
                    b.HasOne("ControleFacil.Api.Damain.Models.NaturezaLancamento", "NaturezaLancamento")
                        .WithMany()
                        .HasForeignKey("IdNL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFacil.Api.Damain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NaturezaLancamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFacil.Api.Damain.Models.NaturezaLancamento", b =>
                {
                    b.HasOne("ControleFacil.Api.Damain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
